import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import cloudinary from "cloudinary"

import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { SideMenu } from "./side-menu"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Photo Album",
  description: "Generated by create next app"
}

export type FolderDataType = {
  folders: {
    name: string
    path: string
  }[]
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const result = (await cloudinary.v2.api.root_folders()) as FolderDataType

  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="border-b">
          <div className="flex h-16 items-center px-4 container mx-auto">
            APP LOGO
            <div className="ml-auto flex items-center space-x-4">
              <Avatar>
                <AvatarImage
                  src="https://github.com/shadcn.png"
                  alt="@shadcn"
                />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
            </div>
          </div>
        </div>

        <div className="flex">
          <SideMenu result={result} />
          <div className="w-full px-4 pt-12">{children}</div>
        </div>
      </body>
    </html>
  )
}
